#ABAXIO ESTOU ESCOLHENDO MINHA IMAGEM BASE PARA RODAR CONTAINER NO DOCKER
FROM Pythom    
#ABAIXO ESTOU CRIANDO A PASTA DE DIRETORIO DA MINHA APLICAÇÃO
WORKDIR  /app
#ABAIXO SELECIONEI O ARQUIVO QUE VAI BAIXAR AS DEPENDENCIAS DO MEU PROJETO
COPY requirements.txt .
#ABAIXO SERÁ O COMANDO PARA EXECUTAR AS INSTALAÇÕES
RUN pip install -r requirements.txt
#ABAIXO USAREI COPY PARA COPIAR O RESTANTE DOS MEUS ARQUIVOS DESTE PROJETO
COPY . /app/
#ABAIXO VOU SINALIZAR EM QUAL PORTA SE COMUNICARA MEU CONTAINER
EXPOSE  5000
#ABAIXO USAREI O COMANDO PARA INICIAR MEU PROJETO
CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "app:app" ]
